# Collaboration Kit backend for clustering support
com.vaadin.experimental.collaborationEngineBackend=true
# Accessible disabled buttons
com.vaadin.experimental.accessibleDisabledButtons=true
# Enable theme component style injection
com.vaadin.experimental.themeComponentStyles=true
# Form Layout auto-responsive mode enabled by default
com.vaadin.experimental.defaultAutoResponsiveFormLayout=true
# Breadcrumbs component
com.vaadin.experimental.breadcrumbsComponent=true
# Copilot experimental features
com.vaadin.experimental.copilotExperimentalFeatures=true
# AI Components
com.vaadin.experimental.aiComponents=true
# Accessible disabled menu items
com.vaadin.experimental.accessibleDisabledMenuItems=true
